# Generated by Django 5.2.5 on 2025-11-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Grama')),
                ('tipo', models.CharField(choices=[('ESMERALDA', 'Grama Esmeralda'), ('SAO_CARLOS', 'Grama São Carlos'), ('BERMUDA', 'Grama Bermuda'), ('SANTO_AGOSTINHO', 'Grama Santo Agostinho')], max_length=20, verbose_name='Tipo')),
                ('preco_por_m2', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço por m²')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('imagem', models.ImageField(upload_to='gramas/', verbose_name='Imagem')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Grama',
                'verbose_name_plural': 'Gramas',
            },
        ),
    ]
